; Input related
JOY_NONE  = %00000000
JOY_UP    = %00000001
JOY_DOWN  = %00000010
JOY_LEFT  = %00000100
JOY_RIGHT = %00001000
JOY_FIRE  = %00010000

JOY_DIR_MASK  = JOY_UP+JOY_DOWN+JOY_LEFT+JOY_RIGHT
JOY_FULL_MASK  = JOY_DIR_MASK+JOY_FIRE

; Graphics related
PAL_BLACK = 0
PAL_BLUE = 1
PAL_RED = 2
PAL_MAGENTA = 3
PAL_GREEN = 4
PAL_CYAN = 5
PAL_YELLOW = 6
PAL_WHITE = 7

; Text mode metrics for 320x200 graphics mode (8x8 per char)
CHAR_COLUMNS = 40
CHAR_ROWS = 25
BORDER_COLUMNS = 4
GAMECHAR_COLUMNS = CHAR_COLUMNS-(2*BORDER_COLUMNS)
GAMEAREA_TOP = 6
GAMEAREA_LEFT = 5
GAMEAREA_BOTTOM = 22

; Cursor advance amounts
CURSOR_ADV_X = 2
CURSOR_ADV_Y = 8

; Player direction
ANIM_IDLE = 0
ANIM_RIGHT = 1
ANIM_LEFT = 2

; Attribute related
ATTR_GRID = 8

ATTR_NOTSOLID = &40 ; Set means not solid
ATTR_REVERSE = &80 ; Set means h-flip

HIT_SOLID = &40
HIT_FIRE = &20
HIT_WATER = &10
HIT_EMPTY = &00

; Frame plotting modes
PLOT_AND = &00
PLOT_OR = &08
PLOT_XOR = &10
PLOT_NULL = &18 ; Invalid - don't plot

; Movement, animation and speed related
DRAGON_NECK_SPEED_Y = 2
GRUNT_SPEED_X = 2
HAWK_SPEED_X = 2

PRISON_LIFT_DELAY = &0A
NOTHING_CARRIED_DELAY = &F0 ; approx 1 second - used twice
INVENTORY_DELAY = &3C
DEATHMSG_DELAY = &FA
DEATH_DELAY = &64
DEATH_ANIM_DELAY = 8
HEART_DELAY = &05
CHEAT_DELAY = &32

; Sound related
SOUND_ON = 0
SOUND_OFF = 1

TUNE_NULL = 0 ; no tune
TUNE_1 = 1 ; title screen
TUNE_2 = 2 ; in-game
TUNE_3 = 3 ; coin collect
TUNE_4 = 4 ; lose a life / heart demo
TUNE_10 = 10 ; ? no idea ?
TUNE_CONT = 255 ; continue playing, tune already set up

TUNE_CHANNELS = 3 ; melody channel for each SID channel

; Room related
OFFMAP = 255

TITLEROOM = 0
BEANSTALKROOM = 1
FIREROOM = 2
HEARTSROOM = 3
UNDERAUSROOM = 7

MARKETSQUAREROOM = 22
STRANGENEWROOM = 23
CHURCHROOM = 24
ILLUSIONROOM = 31

SMUGGLERSROOM = 35
CASTLEDUNGEONROOM = 36
WELLROOM = 39
DRAGONSLAIRROOM = 40
MINESROOM = 41
OUTTOSEAROOM = 45
DOCKSROOM = 46
WAREHOUSE = 47

BROKENBRIDGEROOM = 48
GUARDHOUSEROOM = 49
ARMOROGROOM = 50
MOATROOM = 51
ENTRANCEHALLROOM = 52
GATORROOM = 53
WIDEEYEDDRAGONROOM = 54
TOPWELLROOM = 55
LIFTCONTROLROOM = 56
BASETREEHOUSEROOM = 57
ALLOTMENTROOM = 58
OAKTREEROOM = 59
BASEOFVOLCANOROOM = 60
CRAFTYCLOUDROOM = 63

WESTWINGROOM = 67
BANQUETHALLROOM = 68
EASTWINGROOM = 69
DOZYSHUTROOM = 71
DENZILSPADROOM = 72
DAISYSHUTROOM = 73
GIANTBEANSTALKROOM = 74
CLOUDROUTEROOM = 75
NEARVOLCANOROOM = 76
ACTIVEVOLCANOROOM = 77

WESTTOWERROOM = 83
CASTLESTAIRCASEROOM = 84
EASTTOWERROOM = 85
LONGJUMPCLOUDROOM = 86
MEETINGHALLROOM = 87
LIFTTOELDERSROOM = 88
DIZZYSPARENTSHUTROOM = 89
YETMORECLOUDSROOM = 91
MOREORRIBLECLOUDSROOM = 92
CLOUDCASTLE = 93
DAISYSPRISONROOM = 94

ATTICROOM = 100

GAMESTARTROOM = CASTLEDUNGEONROOM

MAP_WIDTH = 16

; Screen positions
POS_ROOMNAME_X = 44
POS_ROOMNAME_Y = 24

POS_LIVES_X = 46
POS_LIVES_Y = 8

POS_COINCOUNT_X = 78
POS_COINCOUNT_Y = 8

POS_DIZZYLOGO_X = 58
POS_DIZZYLOGO_Y = 57

POS_DIZZYSTART_X = 28
POS_DIZZYSTART_Y = 100

POS_TROLLMINE_X = 90
POS_TROLLMINE_Y = 120

POS_DAISYINHUT_X = 50
POS_DAISYINHUT_Y = 77

; Other constants
MAXFLAMES = 10

SMALLBAGSIZE = 2
BIGBAGSIZE = 4

WATERDISPLACEMENT = 5

FULLHEALTH = 2

NULLPTR = &0000

; 6502 opcodes for polymorphic code
opcode_NOP_imp = &EA
opcode_CLC_imp = &18
opcode_ADC_abs = &6D
opcode_SEC_imp = &38
opcode_SBC_abs = &ED
opcode_EOR_indY = &51
opcode_ORA_indY = &11
