; Graphics related

PAL_BLACK = 0
PAL_BLUE = 1
PAL_RED = 2
PAL_MAGENTA = 3
PAL_GREEN = 4
PAL_CYAN = 5
PAL_YELLOW = 6
PAL_WHITE = 7

; Attribute related
ATTR_GRID = 8

ATTR_NOTSOLID = &40 ; Set means not solid
ATTR_REVERSE = &80 ; Set means h-flip

; Frame plotting modes
PLOT_AND = &00
PLOT_OR = &08
PLOT_XOR = &10
PLOT_NULL = &18 ; Invalid - don't plot

; Room related

OFFMAP = 255

TITLEROOM = 0
BEANSTALKROOM = 1
FIREROOM = 2
HEARTSROOM = 3
UNDERAUSROOM = 7

MARKETSQUAREROOM = 22
STRANGENEWROOM = 23
CHURCHROOM = 24
ILLUSIONROOM = 31

SMUGGLERSROOM = 35
CASTLEDUNGEONROOM = 36
WELLROOM = 39
DRAGONSLAIRROOM = 40
MINESROOM = 41
OUTTOSEAROOM = 45
DOCKSROOM = 46
WAREHOUSE = 47

BROKENBRIDGEROOM = 48
GUARDHOUSEROOM = 49
ARMOROGROOM = 50
MOATROOM = 51
ENTRANCEHALLROOM = 52
GATORROOM = 53
WIDEEYEDDRAGONROOM = 54
TOPWELLROOM = 55
LIFTCONTROLROOM = 56
BASETREEHOUSEROOM = 57
ALLOTMENTROOM = 58
OAKTREEROOM = 59
BASEOFVOLCANOROOM = 60
CRAFTYCLOUDROOM = 63

WESTWINGROOM = 67
BANQUETHALLROOM = 68
EASTWINGROOM = 69
DOZYSHUTROOM = 71
DENZILSPADROOM = 72
DAISYSHUTROOM = 73
GIANTBEANSTALKROOM = 74
CLOUDROUTEROOM = 75
NEARVOLCANOROOM = 76
ACTIVEVOLCANOROOM = 77

WESTTOWERROOM = 83
CASTLESTAIRCASEROOM = 84
EASTTOWERROOM = 85
LONGJUMPCLOUDROOM = 86
MEETINGHALLROOM = 87
LIFTTOELDERSROOM = 88
DIZZYSPARENTSHUTROOM = 89
YETMORECLOUDSROOM = 91
MOREORRIBLECLOUDSROOM = 92
CLOUDCASTLE = 93
DAISYSPRISONROOM = 94

ATTICROOM = 100

GAMESTARTROOM = CASTLEDUNGEONROOM
